export const types = {
     GET_POKEMONS: 'GET_POKEMONS',
     INFO_CARD_THUMB: 'INFO_CARD_THUMB',
     RESET_ALL_POKEMONS:'RESET_ALL_POKEMONS',
     NEXT_POKEMONS: 'NEXT_POKEMONS:',
     LOAD_AUTOCOMPLETE: 'LOAD_AUTOCOMPLETE',
     SEARCH: 'SEARCH',
     SELECTED_POKEMON: 'SELECTED_POKEMON',
     LOADING: 'LOADING',
     ERROR: 'ERROR',
     SEARCH_MODE: 'SEARCH_MODE',
     SEARCH_VALUE: 'SEARCH_VALUE',
     CLEAN_STATE:'CLEAN_STATE'
}

// export default types